runner

diff --git a/slugrunner/runner/init b/slugrunner/runner/init
--- a/slugrunner/runner/init
+++ b/slugrunner/runner/init
@@ -1,27 +1,14 @@
 #!/bin/bash
 ## Load slug from Bind Mount, URL or STDIN
 
+set -x
 set -eo pipefail
 
 export HOME=/app
 mkdir -p "${HOME}"
-
-if [[ -n $(ls -A "${HOME}") ]]; then
-  true
-elif ! [[ -z "${SLUG_URL}" ]]; then
-  curl --silent --location --noproxy "discoverd" --retry 5 --fail "${SLUG_URL}" | tar -xzC "${HOME}"
-  unset SLUG_URL
-else
-  cat | tar -xzC "${HOME}"
-fi
-cd "${HOME}"
-
-## Set home to $HOME
-
-usermod --home $HOME nobody
+cd $HOME
 
 ## Load profile.d and release config
-
 shopt -s nullglob
 mkdir -p .profile.d
 if [[ -s .release ]]; then
@@ -34,18 +21,20 @@ end
 RUBY
 fi
 for file in .profile.d/*; do
-  source "${file}"
+  . "${file}"
 done
 hash -r
 
 ## Inject "start" command to run processes defined in Procfile
-
 case "$1" in
   start)
     if [[ -f Procfile ]]; then
       command=$(ruby -r yaml -e "puts YAML.load_file('Procfile')['$2']")
-    else
+    elif [[ -f .release ]]; then
       command=$(ruby -r yaml -e "puts (YAML.load_file('.release') || {}).fetch('default_process_types', {})['$2']")
+    else
+      echo "file: [Procfile] or [.release] required for command start"
+      exit 1
     fi
     ;;
   *)
@@ -54,6 +43,9 @@ case "$1" in
 esac
 
 ## Run!
-
-chown -R nobody:nogroup .
-exec setuidgid nobody bash -c "${command}"
+if [ "$command" == " ''" ]; then
+	echo -e "empty startup command"
+	exit 1
+fi
+echo -e "startup command: $command"
+exec bash -c "${command}"
